Repository cse110-sp23-group16/cse110-sp23-group16, pull requests merged in 2023-06, with the labels that each got.

#71 Jsdoc
  .github/workflows/documentation.yml
  .github/workflows/formatter.yml
  .github/workflows/tests.yml
  source/pages/skymap_page/Background.js
  source/pages/skymap_page/Constellation.js
  source/pages/skymap_page/skymap.js
Labels: documentation, Priority-high, peer-review, CI/CD

#91 Release notes
  .github/release.yml
Labels: CI/CD

#92 Added Puppeteer Testing Capabilities
  .github/workflows/tests.yml
  source/tests/defaultpuppeteer.test.js
  source/tests/jest.config.json
Labels: CI/CD

#95 UI improvements mostly on response
  source/pages/explanation_page/explanation.css
  source/pages/response_page/response.css
  source/pages/response_page/response.html
  source/pages/response_page/response.js
  source/pages/skymap_page/skymap.js
Labels: UI

#97 UI improvement
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.html
  source/pages/landing_page/landing.css
  source/pages/landing_page/landing.html
  source/pages/landing_page/landing.js
  source/pages/response_page/all_responses.json
  source/pages/response_page/response.css
  source/pages/response_page/response.html
  source/pages/response_page/response.js
  source/pages/skymap_page/skymap.css
  source/pages/skymap_page/skymap.html
  source/pages/thankyou_page/thankyou.css
  source/pages/thankyou_page/thankyou.html
  source/pages/toplevel.css
Labels: feature-dev-code, UI

#96 Explanation page update
  source/assets/pictures/myths/Aries-myth.jpeg
  source/assets/pictures/myths/ArmadilloDragon-myth.jpeg
  source/assets/pictures/myths/CanisMajor-myth.jpeg
  source/assets/pictures/myths/Carina-myth.jpeg
  source/assets/pictures/myths/Crux-myth.jpeg
  source/assets/pictures/myths/Ophiuchus-myth.jpeg
  source/assets/pictures/myths/Orion-myth.jpeg
  source/assets/pictures/myths/UrsaMajor-myth.jpeg
  source/pages/explanation_page/explanation.js
Labels: assets

#107 Added Ursa Major Asset
  source/assets/pictures/constellations/UrsaMajor-explanation.png
  source/assets/pictures/constellations/UrsaMajor-star.png
  source/assets/pictures/constellations/UrsaMajor.png
Labels: assets

#112 Landing page assets
  source/assets/Icons/Career.png
  source/assets/Icons/DailyHoroscope.png
  source/assets/Icons/Health.png
  source/assets/Icons/Relationship.png
  source/pages/landing_page/CrystalBall.png
  source/pages/landing_page/FortuneTeller.png
  source/pages/landing_page/temp_crystal_ball.png
  source/pages/landing_page/temp_teller.png
Labels: assets

#99 Tutorial skymap
  source/pages/skymap_page/skymap.css
  source/pages/skymap_page/skymap.html
  source/pages/skymap_page/skymap.js
Labels: feature-dev-code

#115 Animation
  admin/meetings/060723-Standup.md
  source/assets/Icons/Career.png
  source/assets/Icons/DailyHoroscope.png
  source/assets/Icons/Health.png
  source/assets/Icons/Relationship.png
  source/assets/Teller-shack-background.png
  source/assets/pictures/teller/CrystalBall.png
  source/assets/pictures/teller/FortuneTeller.png
  source/assets/pictures/teller/armadillo-claw-left.png
  source/assets/pictures/teller/armadillo-claw-right.png
  source/assets/pictures/teller/responseTeller.png
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.html
  source/pages/explanation_page/explanation.js
  source/pages/landing_page/landing.css
  source/pages/landing_page/landing.html
  source/pages/landing_page/landing.js
  source/pages/response_page/all_responses.json
  source/pages/response_page/response.css
  source/pages/response_page/response.html
  source/pages/response_page/response.js
  source/pages/response_page/temp_crystal_ball.png
  source/pages/response_page/temp_teller.png
  source/pages/shootingStar.js
  source/pages/shootingStars.css
  source/pages/skymap_page/connected_stars_pair.json
  source/pages/skymap_page/constellation_location.json
  source/pages/skymap_page/skymap.html
  source/pages/skymap_page/skymap.js
  source/pages/thankyou_page/thankyou.css
  source/pages/thankyou_page/thankyou.html
  source/pages/thankyou_page/thankyou.js
  source/pages/toplevel.css
Labels: feature-dev-code

#119 Added one page puppeteer tests for Landing Page
  source/tests/landingpuppeteer.test.js
Labels: CI/CD, tests

#111 Favicon
  source/assets/favicon.ico
  source/pages/explanation_page/explanation.html
  source/pages/landing_page/landing.html
  source/pages/response_page/response.html
  source/pages/skymap_page/skymap.html
  source/pages/thankyou_page/thankyou.html
Labels: enhancement, Priority-mid

#102 Explanation page: Constellation drawing scaled to fill border
  source/assets/pictures/constellations/Aries-explanation.png
  source/assets/pictures/constellations/ArmadilloDragon-explanation.png
  source/assets/pictures/constellations/CanisMajor-explanation.png
  source/assets/pictures/constellations/Carnia-explanation.png
  source/assets/pictures/constellations/Crux-explanation.png
  source/assets/pictures/constellations/Ophiuchus-explanation.png
  source/assets/pictures/constellations/Orion-explanation.png
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.js
Labels: assets

#108 Drawing new constellations on the skymap
  source/pages/skymap_page/connected_stars_pair.json
  source/pages/skymap_page/constellation_location.json
  source/pages/skymap_page/skymap.js
Labels: feature-dev-code

#128 Added Puppeteer single page tests for landing and response page
  source/tests/landingpuppeteer.test.js
  source/tests/response.test.js
  source/tests/responsepuppeteer.test.js
Labels: Priority-high, tests

#131 Readme update
  README.md
Labels: documentation

#133 Jsdocs skymappage
  source/pages/shootingStar.js
  source/pages/skymap_page/Background.js
  source/pages/skymap_page/BackgroundStar.js
  source/pages/skymap_page/Constellation.js
  source/pages/skymap_page/ConstellationStar.js
  source/pages/skymap_page/skymap.js
Labels: documentation

#137 Merging in backend and analytics
  .gitignore
  backend/example-session.md
  backend/index.mjs
  backend/package-lock.json
  backend/package.json
  source/pages/analyticsmanager.js
  source/pages/explanation_page/explanation.html
  source/pages/explanation_page/explanation.js
  source/pages/landing_page/landing.html
  source/pages/landing_page/landing.js
  source/pages/response_page/response.js
  source/pages/skymap_page/skymap.js
  source/pages/thankyou_page/thankyou.js
Labels: feature-dev-code

#127 Puppeteer tests on skymap page along with typo fixes
  source/pages/response_page/all_responses.json
  source/pages/response_page/response.js
  source/pages/skymap_page/connected_stars_pair.json
  source/pages/skymap_page/constellation_location.json
  source/tests/skymap.test.js
Labels: bug, Priority-high, peer-review, tests

#136 Fix UI screen size
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.html
  source/pages/landing_page/landing.css
  source/pages/thankyou_page/thankyou.css
Labels: feature-dev-code

#141 Teller directory refinement
  source/assets/teller/CrystalBall.png
  source/assets/teller/ThankYou_teller.png
  source/assets/teller/armadillo-claw-left.png
  source/assets/teller/armadillo-claw-right.png
Labels: assets

#145 Fixed some minor ui issue
  source/pages/landing_page/landing.css
  source/pages/thankyou_page/thankyou.html
Labels: bug

#148 Document
  README.md
  admin/cipipeline/phase2.md
  specs/adrs/4-VoicingText.md
Labels: documentation, Priority-high

#149 Updated landing page jsdocs
  source/pages/landing_page/landing.js
Labels: documentation
