Repository cse110-sp23-group16/cse110-sp23-group16, pull requests merged in 2023-05, with the labels that each got.

#15 Add skeleton of explanation page
  source/assets/teller.jpg
  source/assets/virgo.jpg
  source/pages/explanation_page/explanation.css
  source/pages/explanation_page/explanation.html
Labels: Priority-mid, feature-dev-code, UI, peer-review

#13 Assets branch
  source/assets/Stargazer-background.psd
  source/assets/Stargazer-preview.png
  source/assets/constellationLocation.md
  source/assets/pictures/Stargazer-asset.png
  source/assets/pictures/Stargazer-background.png
  source/assets/pictures/Stargazer-fillerStars.png
  source/assets/pictures/constellations/Stargazer-Aries.png
  source/assets/pictures/constellations/Stargazer-CanisMajor.png
  source/assets/pictures/constellations/Stargazer-Crux.png
  source/assets/pictures/constellations/Stargazer-Orion.png
Labels: Priority-high, assests, peer-review

#14 add skeleton of thank you page
  source/pages/thankyou_page/thankyou.html
Labels: Priority-mid, feature-dev-code, peer-review

#12 Create detailedDescription.md
  detailedDescription.md
Labels: documentation, good first issue, help wanted, Priority-high, peer-review

#21 Fix placeholder names
  source/assets/placeholder1.jpg
  source/assets/placeholder2.jpg
  source/pages/explanation_page/explanation.html
Labels: Priority-low, assests

#41 added information on how to run the application
  README.md
Labels: documentation, Priority-mid, peer-review

#63 Added UI and fixed thank you page routing issue
  source/pages/landing_page/landing.css
  source/pages/landing_page/landing.html
  source/pages/landing_page/landing.js
  source/pages/landing_page/temp_crystal_ball.png
  source/pages/landing_page/temp_teller.png
  source/pages/response_page/response.css
  source/pages/response_page/response.html
  source/pages/response_page/temp_crystal_ball.png
  source/pages/response_page/temp_teller.png
  source/pages/thankyou_page/thankyou.css
  source/pages/thankyou_page/thankyou.html
  source/pages/thankyou_page/thankyou.js
Labels: Priority-mid, feature-dev-code, peer-review
